<a href="https://colab.research.google.com/github/Syc056/Deep-Learning-with-Python/blob/main/DeepLearningWithPython2_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 신경망의 톱니바퀴 : 텐서 연산

In [6]:
# mnist에서 Dense layer의 예시
from tensorflow.keras import layers
from tensorflow.keras import models

a = models.Sequential()
a.add(layers.Dense(512,activation='relu'))

# 위의 Dense layer는 2D Tensor를 입력으로 받아 2D Tensor를 output으로 배출한다.
# 해당 연산을 자세한 python code로 보면
# -> output = relu(dot(W, input) + b) 와 같은데,
# 3개의 텐서 연산으로 이루어져 있으며 
# 이는 입력 텐서와 텐서 W 간의 점곱(dot),
# 점곱(dot)의 결과인 2D Tensor와 벡터 b 사이의 덧셈,
# 마지막으로 relu 연산이다.
# relu(x) == max(x,0) 이다.

In [7]:
# 원소별 연산

In [8]:
# relu()와 +는 원소별 연산이다.
# 이 연산은 tensor에 있는 각 원소에 독립적으로 적용된다.


In [9]:
def naive_relu(x):
  assert len(x.shape) == 2

  x = x.copy()
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i,j] = max(x[i,j],0)
  return x

In [10]:
def naive_add(x,y):
  assert len(x.shape) ==2
  assert x.shape == y.shape

  x= x.copy()
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i,j] += y[i,j]
  return x

In [11]:
# relu와 add를 파이썬을 이용하여 구현한 코드이다.
# 입력 텐서자체를 바꾸지안힉위하여 x.copy()를 사용하였고,
# assert를 사용하여 x와 y의 shape를 지정하여 2D Tensor로 만들어주었다.
# 같은 원리로 곱셈과 나눗셈을 할수 있다하여 구현해보자.

In [12]:
def naive_mul(x,y):
  assert len(x.shape) == 2
  assert x.shape == y.shape

  x = x.copy()
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i,j] *= y[i,j]
  return x

In [14]:
def naive_mul(x,y):
  assert len(x.shape) == 2
  assert x.shape == y.shape

  x = x.copy()
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i,j] /= y[i,j]
  return x

In [15]:
# 템서 점곱(tensor dot)

In [17]:
import numpy as np

# z = np.dot(x,y)

def naive_vector_dot(x,y):
  assert len(x.shape) == 2 # x = numpy 행렬
  assert len(y.shape) == 1 # y = numpy 벡터
  assert x.shape[0] == y.shape[0]

  z = np.zeros(x.shape[0])
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      z[i] += x[i,j] * y[j]
  return z

def naive_vector_dot(x,y):
  assert len(x.shape) == 2 # x = numpy 행렬
  assert len(y.shape) == 2 # y = numpy 행렬
  assert x.shape[0] == y.shape[0]

  z = np.zeros(x.shape[0],y.shape[1])
  for i in range(x.shape[0]):
    for j in range(y.shape[1]):
      row_x = x[i,:]
      column_y = y[:,j]
      z[i,j] = naive_vector_dot(row_x,column_y)
  return z

In [18]:
# tensor.reshape

In [19]:
x = np.array([[0.,1.],
              [2.,3.],
              [4.,5.]])

In [20]:
print(x.shape)

(3, 2)


In [24]:
x.reshape((6,1))

array([[0.],
       [1.],
       [2.],
       [3.],
       [4.],
       [5.]])

In [26]:
x.reshape(2,3)

array([[0., 1., 2.],
       [3., 4., 5.]])

In [27]:
x = np.transpose(x)

In [28]:
x

array([[0., 2., 4.],
       [1., 3., 5.]])

In [29]:
# x.reshape()를 사용하여 reshape할 수 있으며, 자주사용하는 변환으로 전치(np.transpose)가 있다.